version: '3'
networks:
  groceryshop:
    external: true
volumes:
  mongodb:
    driver:
      local
  mongoconfig:
services:
  order:
    container_name: order
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      domain: ${DOMAIN}
    restart: always
    volumes:
      - ./:/app
    ports:
      - ${SERVER_PORT}:3000
    env_file:
      - .env
    networks:
      - groceryshop
    external_links:
      - auth
      - authredis
      - orderdb
  orderdb:
    image: mongo:4.2.3-bionic
    container_name: orderdb
    command: mongod --auth
    restart: unless-stopped
    ports:
      - 27018:27017
    environment:
      - MONGODB_DATABASE=${DB_DATABASE_NAME}
      - MONGODB_USERNAME=${DB_USERNAME}
      - MONGODB_PASSWORD=${DB_PASSWORD}
    volumes:
      # seeding scripts
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
       # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
       - groceryshop